news_scout_task:
  description: >
    Execute comprehensive news intelligence gathering with mandatory verification protocols:
    
    SEARCH REQUIREMENTS:
    1. Query multiple sources for each topic area (minimum 3 different outlets per topic)
    2. Focus on events from the last 24-48 hours with EXACT UTC timestamps
    3. Prioritize primary sources and official statements
    4. Cross-reference breaking news with established outlets
    
    VERIFICATION WORKFLOW:
    1. Source Assessment:
       - Domain Authority verification (Reuters, AP, BBC, etc. preferred)
       - Bias classification using AllSides/MBFC standards
       - Ownership structure identification
       - Geographic perspective analysis
    
    2. Article Evaluation:
       - Primary source verification (direct quotes, documents, video)
       - Credibility scoring (0-10 scale with justification)
       - Contradiction identification across sources
       - Information warfare detection
    
    3. Quality Gates:
       - Source Reputation ≥ 6/10
       - Article Quality ≥ 5/10
       - Relevance Score ≥ 7/10
       - Exclude articles failing thresholds with explanation
    
    TARGET AREAS:
    - Active conflicts: Ukraine, Gaza, Sudan, Myanmar (verified casualty data required)
    - Strategic incidents: Atrocities, assassinations, coups (independent confirmation)
    - Power dynamics: Alliance shifts, military deployments (official sources)
    - Proxy operations: Irregular warfare, militias (evidence trails)
    - Cyber/Information: State operations, disinformation (technical verification)
    - Diplomatic: Treaties, sanctions, summits (primary documentation)
    
    CONTRADICTION PROTOCOL:
    When sources conflict, document both versions with credibility analysis and potential
    information warfare assessment. Never suppress conflicting accounts.
  expected_output: >
    A comprehensive intelligence brief in structured JSON containing:
    
    {
      "collection_metadata": {
        "start_time_utc": "ISO timestamp",
        "end_time_utc": "ISO timestamp", 
        "total_sources_queried": number,
        "total_articles_evaluated": number,
        "total_articles_selected": number
      },
      "articles": [
        {
          "article_id": "unique identifier",
          "headline": "exact headline",
          "url": "full URL",
          "source": {
            "name": "outlet name",
            "bias_rating": "Left/Lean Left/Center/Lean Right/Right",
            "factual_rating": "Very High/High/Mixed/Low",
            "ownership": "State/Corporate/Independent",
            "geographic_perspective": "Western/Eastern/Regional"
          },
          "timestamps": {
            "event_occurred": "UTC timestamp of actual event",
            "first_reported": "UTC timestamp of initial report",
            "verified_at": "UTC timestamp of confirmation",
            "last_updated": "UTC timestamp of latest update"
          },
          "credibility_scores": {
            "source_reputation": 0-10,
            "article_quality": 0-10,
            "verification_status": 0-10,
            "relevance_score": 0-10,
            "composite_score": 0-10,
            "score_justification": "explanation"
          },
          "content": {
            "summary": "2-3 sentence summary",
            "key_facts": ["fact1", "fact2", "fact3"],
            "primary_sources": ["source1", "source2"],
            "contradictions": "any conflicting reports"
          },
          "strategic_relevance": "why this matters geopolitically",
          "topic_categories": ["category1", "category2"]
        }
      ],
      "excluded_articles": [
        {
          "headline": "article title",
          "source": "outlet",
          "exclusion_reason": "failed quality gate X with score Y"
        }
      ],
      "source_diversity_analysis": {
        "geographic_distribution": {},
        "bias_distribution": {},
        "total_unique_sources": number
      }
    }
  agent: news_scout

geo_analyst_task:
  description: >
    IMMEDIATE ACTION REQUIRED: Begin your analysis with the most significant specific event from news_scout's report.
    
    DO NOT start with historical overview or context-setting.
    DO NOT begin with "To understand X, we must first..."
    DO start with "At [time] on [date], [specific actor] [specific action]..."
    
    Your workflow MUST be:
    1. Identify the 3-5 most strategically significant events from news_scout
    2. For EACH event, analyze:
       - What specific capabilities/intentions it reveals
       - Which actors are involved and their immediate objectives
       - Observable evidence (deployments, statements, economic actions)
    3. ONLY THEN query ChromaDB for historical patterns related to these SPECIFIC events/actors
    4. Compare current events to historical patterns to identify:
       - Continuities (this follows established pattern X)
       - Deviations (this breaks from pattern Y)
       - Novel developments (no historical precedent)
    5. Build strategic inferences from these specific comparisons
    
    The analysis should emphasize:
    1. SPECIFIC timestamped events with exact sources
    2. Actor-specific doctrinal analysis (NOT symmetric comparisons)
    3. Evidence-based inference chains (observable → inference → implication)
    4. Temporal gap acknowledgment (training cutoff to present)
    5. Contradiction reconciliation when sources conflict
    6. Creative pattern recognition (what's NOT being said/done)
    7. Multi-move scenario modeling with probabilities
    
    Apply asymmetric frameworks - China's century planning vs US electoral cycles,
    Russian maskirovka vs EU consensus building. Never collapse into generic analysis.
  expected_output: >
    A rigorously structured analysis that begins with TODAY'S specific events and builds
    strategic understanding from evidence up. Required sections:
    
    - [Knowledge Baseline]: "Training data to [date], bridging gap to [current date] using..."
    - [Current Intelligence]: Specific findings from news_scout with timestamps
    - [Historical Context]: Relevant patterns/assessments from ChromaDB
    - [Evidence Base]: Specific events/statements with timestamps and sources
    - [Actor Doctrines]: How each actor's unique strategic culture shapes their moves
    - [Strategic Inferences]: Creative but evidence-based reading between the lines
    - [Hidden Indicators]: What's not being said/done that reveals intentions
    - [Future Trajectories]: Multiple scenarios with probability assessments and key indicators
    - [Contradiction Reconciliation]: How you handle conflicting intelligence
    - [Learning Delta]: What changed from past GPSE assessments and why
    - [Cascade Modeling]: Multi-move scenarios with probability assessments
    - [Intelligence Gaps]: Critical missing information between training cutoff and present
    
    Every inference must cite specific evidence. Every actor must be analyzed through
    their unique doctrinal lens. Every prediction must include indicators to watch.
  agent: geo_analyst
  context:
    - news_scout_task

communicator_task:
  description: >
    Transform the strategic analysis into a pristine intelligence document with rigorous quality control:
    
    QUALITY CONTROL CHECKLIST (mandatory before saving):
    □ Metadata Verification:
      - All required tags present ([Actors], [Inferred Ends], [Means], etc.)
      - Each tag contains substantive, specific content (no placeholders)
      - Tags accurately reflect the analysis content
    
    □ Section Validation:
      - Executive Summary captures key insights concisely
      - All geo_analyst sections properly incorporated
      - Learning comparisons to past assessments included
      - Scenario implications with probabilities present
    
    □ Temporal Accuracy:
      - All timestamps converted to UTC format
      - Event sequences chronologically accurate
      - Date format consistency throughout
    
    □ Source Attribution:
      - Every claim traces to a specific source
      - Contradiction reconciliations preserved
      - News_scout credibility scores referenced
    
    □ Format Standardization:
      - GGSM-MMDDYY-DailyAnalysis naming convention
      - Proper Markdown hierarchy (#, ##, ###)
      - Consistent spacing and structure
      - No formatting errors or inconsistencies
    
    CROSS-REFERENCE REQUIREMENTS:
    1. Query ChromaDB for related past assessments
    2. Identify prediction accuracy from previous analyses
    3. Note pattern evolutions and strategic shifts
    4. Include "Learning from History" section
    
    ERROR CORRECTION PROTOCOL:
    - Generic language → Replace with specific evidence
    - Missing timestamps → Add from news_scout data
    - Vague attributions → Specify exact sources
    - Symmetric comparisons → Apply actor-specific analysis
    - Unverified claims → Flag or remove
    
    ARCHIVAL EXCELLENCE:
    1. Chunk document intelligently at section boundaries
    2. Tag each chunk with relevant metadata
    3. Create relationship links between related analyses
    4. Generate unique document ID: GPSE_YYYY-MM-DD_NNN
    
    DO NOT save until ALL quality gates pass. Fix any issues before proceeding.
  expected_output: >
    Quality assurance report confirming pristine document creation:
    
    DOCUMENT DETAILS:
    - File Path: strategy_analyses/GGSM-MMDDYY-DailyAnalysis.md
    - Document ID: GPSE_YYYY-MM-DD_NNN
    - Creation Time: [UTC timestamp]
    - Word Count: [total words]
    
    QUALITY VALIDATION:
    ✓ Metadata Completeness: [List all verified tags]
    ✓ Section Compliance: [List all included sections]
    ✓ Temporal Accuracy: [Number of timestamps verified]
    ✓ Source Attribution: [Number of citations included]
    ✓ Format Consistency: [Confirmation of standards met]
    
    CHROMADB ARCHIVAL:
    - Chunks Created: [number] chunks
    - Metadata Tags Applied: [list of tags]
    - Cross-References: [number] links to past analyses
    - Collection Stats: [total documents in database]
    
    LEARNING INTEGRATION:
    - Past Assessments Referenced: [list with IDs]
    - Prediction Validations: [accuracy notes]
    - Pattern Evolution: [key changes identified]
    - Emerging Themes: [new patterns detected]
    
    ISSUES RESOLVED:
    - [List any corrections made during QA]
    - [Note any content enhancements]
    - [Document any clarifications added]
    
    RECOMMENDATIONS:
    - Follow-up Analysis Topics: [based on gaps identified]
    - Collection Priorities: [areas needing more coverage]
    - Pattern Monitoring: [trends to track]
    
    FINAL CONFIRMATION:
    "Document meets all GPSE intelligence standards and has been successfully 
    archived in the strategic knowledge base with full metadata preservation 
    and cross-referencing."
  agent: communicator
  context:
    - geo_analyst_task
